/**
 * COMPLETE TransactionType enum (234 values)
 * For root-level transaction classification
 */
export enum TransactionType {
  UNKNOWN = "UNKNOWN",
  NFT_BID = "NFT_BID",
  NFT_GLOBAL_BID = "NFT_GLOBAL_BID",
  NFT_GLOBAL_BID_CANCELLED = "NFT_GLOBAL_BID_CANCELLED",
  NFT_BID_CANCELLED = "NFT_BID_CANCELLED",
  NFT_LISTING = "NFT_LISTING",
  NFT_CANCEL_LISTING = "NFT_CANCEL_LISTING",
  NFT_SALE = "NFT_SALE",
  NFT_MINT = "NFT_MINT",
  NFT_AUCTION_CREATED = "NFT_AUCTION_CREATED",
  NFT_AUCTION_UPDATED = "NFT_AUCTION_UPDATED",
  NFT_AUCTION_CANCELLED = "NFT_AUCTION_CANCELLED",
  NFT_PARTICIPATION_REWARD = "NFT_PARTICIPATION_REWARD",
  NFT_MINT_REJECTED = "NFT_MINT_REJECTED",
  CREATE_STORE = "CREATE_STORE",
  WHITELIST_CREATOR = "WHITELIST_CREATOR",
  ADD_TO_WHITELIST = "ADD_TO_WHITELIST",
  REMOVE_FROM_WHITELIST = "REMOVE_FROM_WHITELIST",
  AUCTION_MANAGER_CLAIM_BID = "AUCTION_MANAGER_CLAIM_BID",
  EMPTY_PAYMENT_ACCOUNT = "EMPTY_PAYMENT_ACCOUNT",
  UPDATE_PRIMARY_SALE_METADATA = "UPDATE_PRIMARY_SALE_METADATA",
  ADD_TOKEN_TO_VAULT = "ADD_TOKEN_TO_VAULT",
  ACTIVATE_VAULT = "ACTIVATE_VAULT",
  INIT_VAULT = "INIT_VAULT",
  INIT_BANK = "INIT_BANK",
  INIT_STAKE = "INIT_STAKE",
  MERGE_STAKE = "MERGE_STAKE",
  SPLIT_STAKE = "SPLIT_STAKE",
  SET_BANK_FLAGS = "SET_BANK_FLAGS",
  SET_VAULT_LOCK = "SET_VAULT_LOCK",
  UPDATE_VAULT_OWNER = "UPDATE_VAULT_OWNER",
  UPDATE_BANK_MANAGER = "UPDATE_BANK_MANAGER",
  RECORD_RARITY_POINTS = "RECORD_RARITY_POINTS",
  ADD_RARITIES_TO_BANK = "ADD_RARITIES_TO_BANK",
  INIT_FARM = "INIT_FARM",
  INIT_FARMER = "INIT_FARMER",
  REFRESH_FARMER = "REFRESH_FARMER",
  UPDATE_FARM = "UPDATE_FARM",
  AUTHORIZE_FUNDER = "AUTHORIZE_FUNDER",
  DEAUTHORIZE_FUNDER = "DEAUTHORIZE_FUNDER",
  FUND_REWARD = "FUND_REWARD",
  CANCEL_REWARD = "CANCEL_REWARD",
  LOCK_REWARD = "LOCK_REWARD",
  PAYOUT = "PAYOUT",
  VALIDATE_SAFETY_DEPOSIT_BOX_V2 = "VALIDATE_SAFETY_DEPOSIT_BOX_V2",
  SET_AUTHORITY = "SET_AUTHORITY",
  INIT_AUCTION_MANAGER_V2 = "INIT_AUCTION_MANAGER_V2",
  UPDATE_EXTERNAL_PRICE_ACCOUNT = "UPDATE_EXTERNAL_PRICE_ACCOUNT",
  AUCTION_HOUSE_CREATE = "AUCTION_HOUSE_CREATE",
  CLOSE_ESCROW_ACCOUNT = "CLOSE_ESCROW_ACCOUNT",
  WITHDRAW = "WITHDRAW",
  DEPOSIT = "DEPOSIT",
  TRANSFER = "TRANSFER",
  BURN = "BURN",
  BURN_NFT = "BURN_NFT",
  PLATFORM_FEE = "PLATFORM_FEE",
  LOAN = "LOAN",
  RESCIND_LOAN = "RESCIND_LOAN",
  OFFER_LOAN = "OFFER_LOAN",
  CANCEL_OFFER = "CANCEL_OFFER",
  LEND_FOR_NFT = "LEND_FOR_NFT",
  REQUEST_LOAN = "REQUEST_LOAN",
  CANCEL_LOAN_REQUEST = "CANCEL_LOAN_REQUEST",
  BORROW_SOL_FOR_NFT = "BORROW_SOL_FOR_NFT",
  CLAIM_NFT = "CLAIM_NFT",
  REBORROW_SOL_FOR_NFT = "REBORROW_SOL_FOR_NFT",
  REPAY_LOAN = "REPAY_LOAN",
  TAKE_LOAN = "TAKE_LOAN",
  FORECLOSE_LOAN = "FORECLOSE_LOAN",
  UPDATE_OFFER = "UPDATE_OFFER",
  ADD_TO_POOL = "ADD_TO_POOL",
  REMOVE_FROM_POOL = "REMOVE_FROM_POOL",
  CLOSE_POSITION = "CLOSE_POSITION",
  UNLABELED = "UNLABELED",
  CLOSE_ACCOUNT = "CLOSE_ACCOUNT",
  WITHDRAW_GEM = "WITHDRAW_GEM",
  DEPOSIT_GEM = "DEPOSIT_GEM",
  STAKE_TOKEN = "STAKE_TOKEN",
  UNSTAKE_TOKEN = "UNSTAKE_TOKEN",
  STAKE_SOL = "STAKE_SOL",
  UNSTAKE_SOL = "UNSTAKE_SOL",
  CLAIM_REWARDS = "CLAIM_REWARDS",
  BUY_SUBSCRIPTION = "BUY_SUBSCRIPTION",
  SWAP = "SWAP",
  INIT_SWAP = "INIT_SWAP",
  CANCEL_SWAP = "CANCEL_SWAP",
  REJECT_SWAP = "REJECT_SWAP",
  INITIALIZE_ACCOUNT = "INITIALIZE_ACCOUNT",
  TOKEN_MINT = "TOKEN_MINT",
  CREATE_APPRAISAL = "CREATE_APPRAISAL",
  CANDY_MACHINE_WRAP = "CANDY_MACHINE_WRAP",
  CANDY_MACHINE_UNWRAP = "CANDY_MACHINE_UNWRAP",
  CANDY_MACHINE_UPDATE = "CANDY_MACHINE_UPDATE",
  CANDY_MACHINE_ROUTE = "CANDY_MACHINE_ROUTE",
  FRACTIONALIZE = "FRACTIONALIZE",
  DEPOSIT_FRACTIONAL_POOL = "DEPOSIT_FRACTIONAL_POOL",
  FUSE = "FUSE",
  CREATE_RAFFLE = "CREATE_RAFFLE",
  BUY_TICKETS = "BUY_TICKETS",
  UPDATE_ITEM = "UPDATE_ITEM",
  LIST_ITEM = "LIST_ITEM",
  DELIST_ITEM = "DELIST_ITEM",
  ADD_ITEM = "ADD_ITEM",
  CLOSE_ITEM = "CLOSE_ITEM",
  BUY_ITEM = "BUY_ITEM",
  FILL_ORDER = "FILL_ORDER",
  UPDATE_ORDER = "UPDATE_ORDER",
  CREATE_ORDER = "CREATE_ORDER",
  CLOSE_ORDER = "CLOSE_ORDER",
  CANCEL_ORDER = "CANCEL_ORDER",
  KICK_ITEM = "KICK_ITEM",
  UPGRADE_FOX = "UPGRADE_FOX",
  UPGRADE_FOX_REQUEST = "UPGRADE_FOX_REQUEST",
  LOAN_FOX = "LOAN_FOX",
  BORROW_FOX = "BORROW_FOX",
  SWITCH_FOX_REQUEST = "SWITCH_FOX_REQUEST",
  SWITCH_FOX = "SWITCH_FOX",
  CREATE_ESCROW = "CREATE_ESCROW",
  ACCEPT_REQUEST_ARTIST = "ACCEPT_REQUEST_ARTIST",
  CANCEL_ESCROW = "CANCEL_ESCROW",
  ACCEPT_ESCROW_ARTIST = "ACCEPT_ESCROW_ARTIST",
  ACCEPT_ESCROW_USER = "ACCEPT_ESCROW_USER",
  PLACE_BET = "PLACE_BET",
  PLACE_SOL_BET = "PLACE_SOL_BET",
  CREATE_BET = "CREATE_BET",
  INIT_RENT = "INIT_RENT",
  NFT_RENT_LISTING = "NFT_RENT_LISTING",
  NFT_RENT_CANCEL_LISTING = "NFT_RENT_CANCEL_LISTING",
  NFT_RENT_UPDATE_LISTING = "NFT_RENT_UPDATE_LISTING",
  NFT_RENT_ACTIVATE = "NFT_RENT_ACTIVATE",
  NFT_RENT_END = "NFT_RENT_END",
  UPGRADE_PROGRAM_INSTRUCTION = "UPGRADE_PROGRAM_INSTRUCTION",
  FINALIZE_PROGRAM_INSTRUCTION = "FINALIZE_PROGRAM_INSTRUCTION",
  EXECUTE_TRANSACTION = "EXECUTE_TRANSACTION",
  APPROVE_TRANSACTION = "APPROVE_TRANSACTION",
  ACTIVATE_TRANSACTION = "ACTIVATE_TRANSACTION",
  CREATE_TRANSACTION = "CREATE_TRANSACTION",
  CANCEL_TRANSACTION = "CANCEL_TRANSACTION",
  REJECT_TRANSACTION = "REJECT_TRANSACTION",
  ADD_INSTRUCTION = "ADD_INSTRUCTION",
  CREATE_MASTER_EDITION = "CREATE_MASTER_EDITION",
  ATTACH_METADATA = "ATTACH_METADATA",
  REQUEST_PNFT_MIGRATION = "REQUEST_PNFT_MIGRATION",
  START_PNFT_MIGRATION = "START_PNFT_MIGRATION",
  MIGRATE_TO_PNFT = "MIGRATE_TO_PNFT",
  UPDATE_RAFFLE = "UPDATE_RAFFLE",
  CREATE_MERKLE_TREE = "CREATE_MERKLE_TREE",
  DELEGATE_MERKLE_TREE = "DELEGATE_MERKLE_TREE",
  COMPRESSED_NFT_MINT = "COMPRESSED_NFT_MINT",
  COMPRESSED_NFT_TRANSFER = "COMPRESSED_NFT_TRANSFER",
  COMPRESSED_NFT_REDEEM = "COMPRESSED_NFT_REDEEM",
  COMPRESSED_NFT_CANCEL_REDEEM = "COMPRESSED_NFT_CANCEL_REDEEM",
  COMPRESSED_NFT_BURN = "COMPRESSED_NFT_BURN",
  COMPRESSED_NFT_VERIFY_CREATOR = "COMPRESSED_NFT_VERIFY_CREATOR",
  COMPRESSED_NFT_UNVERIFY_CREATOR = "COMPRESSED_NFT_UNVERIFY_CREATOR",
  COMPRESSED_NFT_VERIFY_COLLECTION = "COMPRESSED_NFT_VERIFY_COLLECTION",
  COMPRESSED_NFT_UNVERIFY_COLLECTION = "COMPRESSED_NFT_UNVERIFY_COLLECTION",
  COMPRESSED_NFT_SET_VERIFY_COLLECTION = "COMPRESSED_NFT_SET_VERIFY_COLLECTION",
  DECOMPRESS_NFT = "DECOMPRESS_NFT",
  COMPRESS_NFT = "COMPRESS_NFT",
  COMPRESSED_NFT_DELEGATE = "COMPRESSED_NFT_DELEGATE",
  CREATE_POOL = "CREATE_POOL",
  DISTRIBUTE_COMPRESSION_REWARDS = "DISTRIBUTE_COMPRESSION_REWARDS",
  CHANGE_COMIC_STATE = "CHANGE_COMIC_STATE",
  UPDATE_RECORD_AUTHORITY_DATA = "UPDATE_RECORD_AUTHORITY_DATA",
  CREATE_AVATAR_CLASS = "CREATE_AVATAR_CLASS",
  CREATE_AVATAR = "CREATE_AVATAR",
  CREATE_TRAIT = "CREATE_TRAIT",
  CREATE_PAYMENT_METHOD = "CREATE_PAYMENT_METHOD",
  EQUIP_TRAIT = "EQUIP_TRAIT",
  EQUIP_TRAIT_AUTHORITY = "EQUIP_TRAIT_AUTHORITY",
  REMOVE_TRAIT = "REMOVE_TRAIT",
  REMOVE_TRAIT_AUTHORITY = "REMOVE_TRAIT_AUTHORITY",
  UPDATE_TRAIT_VARIANT = "UPDATE_TRAIT_VARIANT",
  UPDATE_TRAIT_VARIANT_AUTHORITY = "UPDATE_TRAIT_VARIANT_AUTHORITY",
  UPDATE_CLASS_VARIANT_AUTHORITY = "UPDATE_CLASS_VARIANT_AUTHORITY",
  UPDATE_TRAIT_VARIANT_METADATA = "UPDATE_TRAIT_VARIANT_METADATA",
  UPDATE_CLASS_VARIANT_METADATA = "UPDATE_CLASS_VARIANT_METADATA",
  BEGIN_VARIANT_UPDATE = "BEGIN_VARIANT_UPDATE",
  BEGIN_TRAIT_UPDATE = "BEGIN_TRAIT_UPDATE",
  CANCEL_UPDATE = "CANCEL_UPDATE",
  UPDATE_VARIANT = "UPDATE_VARIANT",
  TRANSFER_PAYMENT = "TRANSFER_PAYMENT",
  BURN_PAYMENT = "BURN_PAYMENT",
  BURN_PAYMENT_TREE = "BURN_PAYMENT_TREE",
  TRANSFER_PAYMENT_TREE = "TRANSFER_PAYMENT_TREE",
  ADD_PAYMENT_MINT_PAYMENT_METHOD = "ADD_PAYMENT_MINT_PAYMENT_METHOD",
  ADD_TRAIT_CONFLICTS = "ADD_TRAIT_CONFLICTS",
  VERIFY_PAYMENT_MINT = "VERIFY_PAYMENT_MINT",
  VERIFY_PAYMENT_MINT_TEST = "VERIFY_PAYMENT_MINT_TEST",
  BOUND_HADO_MARKET_TO_FRAKT_MARKET = "BOUND_HADO_MARKET_TO_FRAKT_MARKET",
  DEPOSIT_TO_BOND_OFFER_STANDARD = "DEPOSIT_TO_BOND_OFFER_STANDARD",
  WITHDRAW_FROM_BOND_OFFER_STANDARD = "WITHDRAW_FROM_BOND_OFFER_STANDARD",
  INITIALIZE_HADO_MARKET = "INITIALIZE_HADO_MARKET",
  FINISH_HADO_MARKET = "FINISH_HADO_MARKET",
  UPDATE_HADO_MARKET_FEE = "UPDATE_HADO_MARKET_FEE",
  REMOVE_BOND_OFFER_V2 = "REMOVE_BOND_OFFER_V2",
  REPAY_FBOND_TO_TRADE_TRANSACTIONS = "REPAY_FBOND_TO_TRADE_TRANSACTIONS",
  EXIT_VALIDATE_AND_SELL_TO_BOND_OFFERS_V2 = "EXIT_VALIDATE_AND_SELL_TO_BOND_OFFERS_V2",
  REFINANCE_TO_BOND_OFFERS_V2 = "REFINANCE_TO_BOND_OFFERS_V2",
  CREATE_BOND_AND_SELL_TO_OFFERS = "CREATE_BOND_AND_SELL_TO_OFFERS",
  LIQUIDATE_BOND_ON_AUCTION_PNFT = "LIQUIDATE_BOND_ON_AUCTION_PNFT",
  CLAIM_NFT_BY_LENDER_PNFT = "CLAIM_NFT_BY_LENDER_PNFT",
  CREATE_BOND_AND_SELL_TO_OFFERS_FOR_TEST = "CREATE_BOND_AND_SELL_TO_OFFERS_FOR_TEST",
  INITIALIZE_FLASH_LOAN_POOL = "INITIALIZE_FLASH_LOAN_POOL",
  DEPOSIT_SOL_TO_FLASH_LOAN_POOL = "DEPOSIT_SOL_TO_FLASH_LOAN_POOL",
  WITHDRAW_SOL_FROM_FLASH_LOAN_POOL = "WITHDRAW_SOL_FROM_FLASH_LOAN_POOL",
  TAKE_FLASH_LOAN = "TAKE_FLASH_LOAN",
  REPAY_FLASH_LOAN = "REPAY_FLASH_LOAN",
  CREATE_BOND_OFFER_STANDARD = "CREATE_BOND_OFFER_STANDARD",
  UPDATE_BOND_OFFER_STANDARD = "UPDATE_BOND_OFFER_STANDARD",
  STAKE_BANX = "STAKE_BANX",
  UNSTAKE_BANX = "UNSTAKE_BANX",
  UNSUB_OR_HARVEST_WEEKS = "UNSUB_OR_HARVEST_WEEKS",
  UNSUB_OR_HARVEST_WEEKS_ENHANCED = "UNSUB_OR_HARVEST_WEEKS_ENHANCED",
  UPDATE_STAKING_SETTINGS = "UPDATE_STAKING_SETTINGS",
  MAP_BANX_TO_POINTS = "MAP_BANX_TO_POINTS",
  PATCH_BROKEN_USER_STAKES = "PATCH_BROKEN_USER_STAKES",
  DEPOSIT_TO_REWARDS_VAULT = "DEPOSIT_TO_REWARDS_VAULT",
  WITHDRAW_REWARDS_FROM_VAULT = "WITHDRAW_REWARDS_FROM_VAULT",
  REFINANCE_FBOND_BY_LENDER = "REFINANCE_FBOND_BY_LENDER",
  SELL_STAKED_BANX_TO_OFFERS = "SELL_STAKED_BANX_TO_OFFERS",
  REPAY_STAKED_BANX = "REPAY_STAKED_BANX",
  CREATE_PERPETUAL_BOND_OFFER = "CREATE_PERPETUAL_BOND_OFFER",
  REMOVE_PERPETUAL_OFFER = "REMOVE_PERPETUAL_OFFER",
  REPAY_PERPETUAL_LOAN = "REPAY_PERPETUAL_LOAN",
  REFINANCE_PERPETUAL_LOAN = "REFINANCE_PERPETUAL_LOAN",
  CREATE_BOND_AND_SELL_TO_OFFERS_CNFT = "CREATE_BOND_AND_SELL_TO_OFFERS_CNFT",
  REPAY_FBOND_TO_TRADE_TRANSACTIONS_CNFT = "REPAY_FBOND_TO_TRADE_TRANSACTIONS_CNFT",
  REFINANCE_TO_BOND_OFFERS_V2_CNFT = "REFINANCE_TO_BOND_OFFERS_V2_CNFT",
  CLAIM_NFT_BY_LENDER_CNFT = "CLAIM_NFT_BY_LENDER_CNFT",
  LIQUIDATE_BOND_ON_AUCTION_CNFT = "LIQUIDATE_BOND_ON_AUCTION_CNFT",
  MAKE_PERPETUAL_MARKET = "MAKE_PERPETUAL_MARKET",
  UPDATE_PERPETUAL_MARKET = "UPDATE_PERPETUAL_MARKET",
  UPDATE_PERPETUAL_OFFER = "UPDATE_PERPETUAL_OFFER",
  UPDATE_INTEREST_PERPETUAL_MARKET = "UPDATE_INTEREST_PERPETUAL_MARKET",
  SORROW_PERPETUAL = "SORROW_PERPETUAL",
  CLAIM_PERPETUAL_LOAN = "CLAIM_PERPETUAL_LOAN",
  TERMINATE_PERPETUAL_LOAN = "TERMINATE_PERPETUAL_LOAN",
  INSTANT_REFINANCE_PERPETUAL_LOAN = "INSTANT_REFINANCE_PERPETUAL_LOAN",
  BORROW_STAKED_BANX_PERPETUAL = "BORROW_STAKED_BANX_PERPETUAL",
  REPAY_STAKED_BANX_PERPETUAL_LOAN = "REPAY_STAKED_BANX_PERPETUAL_LOAN",
  BORROW_CNFT_PERPETUAL = "BORROW_CNFT_PERPETUAL",
  REPAY_CNFT_PERPETUAL_LOAN = "REPAY_CNFT_PERPETUAL_LOAN",
  CLAIM_CNFT_PERPETUAL_LOAN = "CLAIM_CNFT_PERPETUAL_LOAN",
  REPAY_PARTIAL_PERPETUAL_LOAN = "REPAY_PARTIAL_PERPETUAL_LOAN",
  CREATE_COLLECTION = "CREATE_COLLECTION",
  UPDATE_COLLECTION = "UPDATE_COLLECTION",
  UPDATE_COLLECTION_OR_CREATOR = "UPDATE_COLLECTION_OR_CREATOR",
  UPDATE_FLOOR = "UPDATE_FLOOR",
  DELETE_COLLECTION = "DELETE_COLLECTION",
  CREATE_STATS = "CREATE_STATS",
  UPDATE_STATS = "UPDATE_STATS",
  CLEAN = "CLEAN",
  EXPIRE = "EXPIRE",
  FIX_POOL = "FIX_POOL",
  ADMIN_SYNC_LIQUIDITY = "ADMIN_SYNC_LIQUIDITY",
  CLOSE_POOL = "CLOSE_POOL",
  UPDATE_POOL = "UPDATE_POOL",
  UPDATE_POOL_COLLECTIONS = "UPDATE_POOL_COLLECTIONS",
  UPDATE_POOL_STATUS = "UPDATE_POOL_STATUS",
  UPDATE_POOL_MORTGAGE = "UPDATE_POOL_MORTGAGE",
  UPDATE_USABLE_AMOUNT = "UPDATE_USABLE_AMOUNT",
  UPDATE_POOL_WHITELIST = "UPDATE_POOL_WHITELIST",
  ADD_LIQUIDITY = "ADD_LIQUIDITY",
  SYNC_LIQUIDITY = "SYNC_LIQUIDITY",
  WITHDRAW_LIQUIDITY = "WITHDRAW_LIQUIDITY",
  TAKE_COMPRESSED_LOAN = "TAKE_COMPRESSED_LOAN",
  REPAY = "REPAY",
  REPAY_COMPRESSED = "REPAY_COMPRESSED",
  LIQUIDATE = "LIQUIDATE",
  TAKE_MORTGAGE = "TAKE_MORTGAGE",
  FREEZE = "FREEZE",
  UNFREEZE = "UNFREEZE",
  SELL_LOAN = "SELL_LOAN",
  BUY_LOAN = "BUY_LOAN",
  EXTEND_LOAN = "EXTEND_LOAN",
  SELL_NFT = "SELL_NFT",
  PROPOSE_LOAN = "PROPOSE_LOAN",
  CANCEL_PROPOSAL = "CANCEL_PROPOSAL",
  POOL_CANCEL_PROPOSAL = "POOL_CANCEL_PROPOSAL",
  ACCEPT_PROPOSAL = "ACCEPT_PROPOSAL",
  EXECUTE_LOAN = "EXECUTE_LOAN",
  EXECUTE_MORTGAGE = "EXECUTE_MORTGAGE",
  LIST_NFT = "LIST_NFT",
  DELIST_NFT = "DELIST_NFT",
  CLAIM_SALE = "CLAIM_SALE",
  BOT_LIQUIDATE = "BOT_LIQUIDATE",
  BOT_UNFREEZE = "BOT_UNFREEZE",
  BOT_SELL = "BOT_SELL",
  BOT_DELIST = "BOT_DELIST",
  BOT_CLAIM_SALE = "BOT_CLAIM_SALE",
}

/**
 * NFT Event Type enum (37 values)
 * For events.nft.type field
 */
export enum NFTEventType {
  NFT_BID = "NFT_BID",
  NFT_GLOBAL_BID = "NFT_GLOBAL_BID",
  NFT_GLOBAL_BID_CANCELLED = "NFT_GLOBAL_BID_CANCELLED",
  NFT_BID_CANCELLED = "NFT_BID_CANCELLED",
  NFT_LISTING = "NFT_LISTING",
  NFT_CANCEL_LISTING = "NFT_CANCEL_LISTING",
  NFT_SALE = "NFT_SALE",
  NFT_MINT = "NFT_MINT",
  NFT_AUCTION_CREATED = "NFT_AUCTION_CREATED",
  NFT_AUCTION_UPDATED = "NFT_AUCTION_UPDATED",
  NFT_AUCTION_CANCELLED = "NFT_AUCTION_CANCELLED",
  NFT_PARTICIPATION_REWARD = "NFT_PARTICIPATION_REWARD",
  NFT_MINT_REJECTED = "NFT_MINT_REJECTED",
  BURN_NFT = "BURN_NFT",
  NFT_RENT_LISTING = "NFT_RENT_LISTING",
  NFT_RENT_CANCEL_LISTING = "NFT_RENT_CANCEL_LISTING",
  NFT_RENT_UPDATE_LISTING = "NFT_RENT_UPDATE_LISTING",
  NFT_RENT_ACTIVATE = "NFT_RENT_ACTIVATE",
  NFT_RENT_END = "NFT_RENT_END",
  ATTACH_METADATA = "ATTACH_METADATA",
  MIGRATE_TO_PNFT = "MIGRATE_TO_PNFT",
  CREATE_POOL = "CREATE_POOL",
  COMPRESSED_NFT_MINT = "COMPRESSED_NFT_MINT",
  COMPRESSED_NFT_TRANSFER = "COMPRESSED_NFT_TRANSFER",
  COMPRESSED_NFT_REDEEM = "COMPRESSED_NFT_REDEEM",
  COMPRESSED_NFT_CANCEL_REDEEM = "COMPRESSED_NFT_CANCEL_REDEEM",
  COMPRESSED_NFT_BURN = "COMPRESSED_NFT_BURN",
  COMPRESSED_NFT_VERIFY_CREATOR = "COMPRESSED_NFT_VERIFY_CREATOR",
  COMPRESSED_NFT_UNVERIFY_CREATOR = "COMPRESSED_NFT_UNVERIFY_CREATOR",
  COMPRESSED_NFT_VERIFY_COLLECTION = "COMPRESSED_NFT_VERIFY_COLLECTION",
  COMPRESSED_NFT_UNVERIFY_COLLECTION = "COMPRESSED_NFT_UNVERIFY_COLLECTION",
  COMPRESSED_NFT_SET_VERIFY_COLLECTION = "COMPRESSED_NFT_SET_VERIFY_COLLECTION",
  DECOMPRESS_NFT = "DECOMPRESS_NFT",
  COMPRESS_NFT = "COMPRESS_NFT",
  COMPRESSED_NFT_DELEGATE = "COMPRESSED_NFT_DELEGATE",
  DELEGATE_MERKLE_TREE = "DELEGATE_MERKLE_TREE",
}

/**
 * Main TransactionSource enum (98 values)
 * For root-level source field
 */
export enum TransactionSource {
  FORM_FUNCTION = "FORM_FUNCTION",
  EXCHANGE_ART = "EXCHANGE_ART",
  CANDY_MACHINE_V3 = "CANDY_MACHINE_V3",
  CANDY_MACHINE_V2 = "CANDY_MACHINE_V2",
  CANDY_MACHINE_V1 = "CANDY_MACHINE_V1",
  UNKNOWN = "UNKNOWN",
  SOLANART = "SOLANART",
  SOLSEA = "SOLSEA",
  MAGIC_EDEN = "MAGIC_EDEN",
  HOLAPLEX = "HOLAPLEX",
  METAPLEX = "METAPLEX",
  OPENSEA = "OPENSEA",
  SOLANA_PROGRAM_LIBRARY = "SOLANA_PROGRAM_LIBRARY",
  ANCHOR = "ANCHOR",
  PHANTOM = "PHANTOM",
  SYSTEM_PROGRAM = "SYSTEM_PROGRAM",
  STAKE_PROGRAM = "STAKE_PROGRAM",
  COINBASE = "COINBASE",
  CORAL_CUBE = "CORAL_CUBE",
  HEDGE = "HEDGE",
  LAUNCH_MY_NFT = "LAUNCH_MY_NFT",
  GEM_BANK = "GEM_BANK",
  GEM_FARM = "GEM_FARM",
  DEGODS = "DEGODS",
  BSL = "BSL",
  YAWWW = "YAWWW",
  ATADIA = "ATADIA",
  DIGITAL_EYES = "DIGITAL_EYES",
  HYPERSPACE = "HYPERSPACE",
  TENSOR = "TENSOR",
  BIFROST = "BIFROST",
  JUPITER = "JUPITER",
  MERCURIAL = "MERCURIAL",
  SABER = "SABER",
  SERUM = "SERUM",
  STEP_FINANCE = "STEP_FINANCE",
  CROPPER = "CROPPER",
  RAYDIUM = "RAYDIUM",
  ALDRIN = "ALDRIN",
  CREMA = "CREMA",
  LIFINITY = "LIFINITY",
  CYKURA = "CYKURA",
  ORCA = "ORCA",
  MARINADE = "MARINADE",
  STEPN = "STEPN",
  SENCHA = "SENCHA",
  SAROS = "SAROS",
  ENGLISH_AUCTION = "ENGLISH_AUCTION",
  FOXY = "FOXY",
  HADESWAP = "HADESWAP",
  FOXY_STAKING = "FOXY_STAKING",
  FOXY_RAFFLE = "FOXY_RAFFLE",
  FOXY_TOKEN_MARKET = "FOXY_TOKEN_MARKET",
  FOXY_MISSIONS = "FOXY_MISSIONS",
  FOXY_MARMALADE = "FOXY_MARMALADE",
  FOXY_COINFLIP = "FOXY_COINFLIP",
  FOXY_AUCTION = "FOXY_AUCTION",
  CITRUS = "CITRUS",
  ZETA = "ZETA",
  ELIXIR = "ELIXIR",
  ELIXIR_LAUNCHPAD = "ELIXIR_LAUNCHPAD",
  CARDINAL_RENT = "CARDINAL_RENT",
  CARDINAL_STAKING = "CARDINAL_STAKING",
  BPF_LOADER = "BPF_LOADER",
  BPF_UPGRADEABLE_LOADER = "BPF_UPGRADEABLE_LOADER",
  SQUADS = "SQUADS",
  SHARKY_FI = "SHARKY_FI",
  OPEN_CREATOR = "OPEN_CREATOR",
  PROTOCOL = "PROTOCOL",
  BUBBLEGUM = "BUBBLEGUM",
  NOVA = "NOVA",
  D_READER = "D_READER",
  RAINDROPS = "RAINDROPS",
  W_SOL = "W_SOL",
  DUST = "DUST",
  SOLI = "SOLI",
  USDC = "USDC",
  FLWR = "FLWR",
  HDG = "HDG",
  MEAN = "MEAN",
  UXD = "UXD",
  SHDW = "SHDW",
  POLIS = "POLIS",
  ATLAS = "ATLAS",
  USH = "USH",
  TRTLS = "TRTLS",
  RUNNER = "RUNNER",
  INVICTUS = "INVICTUS",
}

/**
 * NFT Event Source enum (32 values)
 * For events.nft.source field
 */
export enum NFTEventSource {
  FORM_FUNCTION = "FORM_FUNCTION",
  EXCHANGE_ART = "EXCHANGE_ART",
  CANDY_MACHINE_V3 = "CANDY_MACHINE_V3",
  CANDY_MACHINE_V2 = "CANDY_MACHINE_V2",
  CANDY_MACHINE_V1 = "CANDY_MACHINE_V1",
  SOLANART = "SOLANART",
  SOLSEA = "SOLSEA",
  MAGIC_EDEN = "MAGIC_EDEN",
  HOLAPLEX = "HOLAPLEX",
  METAPLEX = "METAPLEX",
  OPENSEA = "OPENSEA",
  CORAL_CUBE = "CORAL_CUBE",
  LAUNCH_MY_NFT = "LAUNCH_MY_NFT",
  DIGITAL_EYES = "DIGITAL_EYES",
  HYPERSPACE = "HYPERSPACE",
  TENSOR = "TENSOR",
  HADESWAP = "HADESWAP",
  FOXY = "FOXY",
  FOXY_STAKING = "FOXY_STAKING",
  FOXY_RAFFLE = "FOXY_RAFFLE",
  FOXY_TOKEN_MARKET = "FOXY_TOKEN_MARKET",
  FOXY_MISSIONS = "FOXY_MISSIONS",
  FOXY_MARMALADE = "FOXY_MARMALADE",
  FOXY_COINFLIP = "FOXY_COINFLIP",
  FOXY_AUCTION = "FOXY_AUCTION",
  CARDINAL_RENT = "CARDINAL_RENT",
  BUBBLEGUM = "BUBBLEGUM",
  SHARKY_FI = "SHARKY_FI",
  BIFROST = "BIFROST",
  ATADIA = "ATADIA",
  ENGLISH_AUCTION = "ENGLISH_AUCTION",
  PHANTOM = "PHANTOM",
}

export interface NativeTransfer {
  fromUserAccount: string;
  toUserAccount: string;
  amount: number;
}

export interface TokenTransfer {
  fromUserAccount: string;
  toUserAccount?: string;
  fromTokenAccount?: string;
  toTokenAccount?: string;
  tokenAmount?: number;
  mint: string;
}

export interface TokenBalanceChange {
  userAccount?: string;
  tokenAccount: string;
  mint?: string;
  rawTokenAmount?: {
    tokenAmount: string;
    decimals: number;
  };
}

export interface AccountData {
  account: string;
  nativeBalanceChange?: number;
  tokenBalanceChanges?: TokenBalanceChange[];
}

export interface Instruction {
  accounts: string[];
  data: string;
  programId: string;
  innerInstructions?: Array<{
    accounts: string[];
    data?: string;
    programId?: string;
  }>;
}

export interface NFTDetail {
  mint?: string;
  tokenStandard?:
    | "NonFungible"
    | "FungibleAsset"
    | "Fungible"
    | "NonFungibleEdition";
}

export interface NFTEvent {
  description?: string;
  type?: NFTEventType;
  source?: NFTEventSource;
  amount?: number;
  saleType?:
    | "AUCTION"
    | "INSTANT_SALE"
    | "OFFER"
    | "GLOBAL_OFFER"
    | "MINT"
    | "UNKNOWN";
  buyer?: string;
  seller?: string;
  staker?: string;
  nfts?: NFTDetail[];
}

export interface SwapEvent {
  nativeInput?: { amount: number };
  nativeOutput?: { amount: number };
  tokenInputs?: Array<{ mint: string; amount: number }>;
  tokenOutputs?: Array<{ mint: string; amount: number }>;
  tokenFees?: Array<{ mint: string; amount: number }>;
  nativeFees?: Array<{ amount: number }>;
  innerSwaps?: Array<{ inputMint: string; outputMint: string; amount: number }>;
}

export interface CompressedEvent {
  type:
    | "COMPRESSED_NFT_MINT"
    | "COMPRESSED_NFT_TRANSFER"
    | "CREATE_MERKLE_TREE"
    | "COMPRESSED_NFT_REDEEM"
    | "COMPRESSED_NFT_CANCEL_REDEEM"
    | "COMPRESSED_NFT_BURN"
    | "COMPRESSED_NFT_DELEGATE"
    | "DELEGATE_MERKLE_TREE"
    | "COMPRESSED_NFT_VERIFY_CREATOR"
    | "COMPRESSED_NFT_UNVERIFY_CREATOR"
    | "COMPRESSED_NFT_VERIFY_COLLECTION"
    | "COMPRESSED_NFT_UNVERIFY_COLLECTION"
    | "COMPRESSED_NFT_SET_VERIFY_COLLECTION"
    | "DECOMPRESS_NFT"
    | "COMPRESS_NFT";
  treeId?: string;
  assetId: string;
  leafIndex?: number;
  instructionIndex?: number;
  innerInstructionIndex?: number;
  newLeafOwner: string;
  oldLeafOwner?: string;
}

export interface HeliusTransaction {
  description?: string;
  type?: TransactionType;
  source: TransactionSource;
  fee: number;
  feePayer?: string;
  signature: string;
  slot?: number;
  timestamp?: number;
  nativeTransfers?: NativeTransfer[];
  tokenTransfers?: TokenTransfer[];
  accountData?: AccountData[];
  transactionError?: {
    error: string;
  };
  instructions?: Instruction[];
  events?: {
    nft?: NFTEvent;
    swap?: SwapEvent;
    compressed?: CompressedEvent;
  };
}

//   export type HeliusTransactionResponse = HeliusTransaction[];
